app/routes/admin_routes.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for, 
    flash, 
    send_from_directory, 
    session
    )


admin_bp = Blueprint('admin', __name__, static_folder='../templates/admin')


@admin_bp.route('/admin', methods=['GET'])
def show_admin_home():
    if 'username' in session:
        return render_template('admin/admin-base.html') 
    else:
        return redirect(url_for('login.show_login'))


@admin_bp.route('/admin/gestor-tramite', methods=['GET'])
def show_admin_gtramite():
    return render_template('admin/gestor-tramite/gestor-tramite.html')



@admin_bp.route('/admin/static/<path:filename>')
def admin_static(filename):
    return send_from_directory(admin_bp.static_folder, filename)

app/routes/gestor_tramite_routes.py
from flask import Blueprint, jsonify, request, render_template
import app.gestores.gestor_tramite_gestor as gestor_tramite_gestor
from datetime import datetime


gestor_tramite_bp = Blueprint('gestor_tramite', __name__, static_folder='../templates/tramite')


@gestor_tramite_bp.route('/gestor_tramite/obtener_persona/<carnet>', methods=['GET'])
def obtener_persona(carnet):
    try:
        persona = gestor_tramite_gestor.obtener_persona(carnet)
        if persona:
            return jsonify(persona._asdict())
        else:
            return jsonify({"error": "Persona no encontrada"}), 404
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@gestor_tramite_bp.route('/gestor_tramite/registrar_tramite', methods=['POST'])
def registrar_tramite():
    data = request.get_json()
    
    tramitador_id = data.get('tramitador_id')
    propietario_id = data.get('propietario_id')
    tipo_tramite_id = data.get('tipo_tramite')
    nro_patente = data.get('nro_patente')
    descripcion_documentos_entregados = data.get('descripcion_documentos_entregados')
    fecha_estimada_entrega = data.get('fecha_estimada_entrega')
    fecha_inicio = datetime.now() 

    # Instanciar Tramite
    tramite = gestor_tramite_gestor.Tramite(
        id=None,  # Si no tienes un ID para el nuevo trámite
        fecha_inicio=fecha_inicio.strftime("%Y-%m-%d"),  # Formato de fecha
        fecha_fin_probable=fecha_estimada_entrega,
        descripcion_documentos=descripcion_documentos_entregados,
        nro_patente=nro_patente,
        observacion="",
        id_estado=1,
        id_tipo_tramite=tipo_tramite_id,
        id_propietario=propietario_id,
        id_gestor_tramite=tramitador_id,
        id_operador=4, # Aqui cambiar para obtener el ID Operador dependiendo del usuario operador que se haya logueado.
        nombre_estado=None
    )

    if gestor_tramite_gestor.registrar_tramite(tramite):
        return jsonify({"message": "Trámite registrado correctamente"}), 201
    else:
        return jsonify({"message": "Error al registrar el trámite"}), 500


@gestor_tramite_bp.route('/gestor_tramite/registrar_persona', methods=['POST'])
def registrar_persona():
    data = request.get_json()
    persona = gestor_tramite_gestor.Persona(
        id=None,
        ci=data.get('carnet'),
        nombre=data.get('nombre'),
        ap_paterno=data.get('ap_paterno'),
        ap_materno=data.get('ap_materno'),
        telefono=data.get('tel'),
        direccion=data.get('direccion'),
        id_usuario=None
    )
    res = gestor_tramite_gestor.registrar_persona(persona)
    if res:
        return jsonify({"message": "Persona registrada correctamente"}), 201
    else:
        return jsonify({"message": "Error al registrar persona"}), 500


@gestor_tramite_bp.route('/ver_tramite', methods=['GET'])
def show_ver_tramite_get():
    return render_template('tramite/tramite.html')

@gestor_tramite_bp.route('/ver_tramite', methods=['POST'])
def show_ver_tramite_post():
    cod = request.form.get('codigo')
    tramite = gestor_tramite_gestor.obtener_datos_tramite(cod)
    
    if tramite: 
        return render_template('tramite/tramite.html', tramite = tramite)
    else: 
        return render_template('tramite/tramite.html', tramite = None)

app/routes/login_routes.py
from flask import (
    Blueprint, 
    render_template, 
    request, 
    redirect, 
    url_for, 
    flash, 
    send_from_directory,
    session)
import app.gestores.login_gestor as login_gestor # Importamos el modulo de login_gestor

# login_bp es un Blueprint sirve para manejar rutas
login_bp = Blueprint('login', __name__, static_folder='../templates/login')


@login_bp.route('/login', methods=['GET'])
def show_login():
    return render_template('login/login.html') 


@login_bp.route('/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')
    
    # Llamamos a la funcion validar_credenciales del modulo login_gestor
    if login_gestor.validar_credenciales(username, password):

        tipo_user = 'ADM' # Esto manejar por base de datos
        if tipo_user == 'ADM':
            session['Nombre_Completo'] = ''
            session['username'] = username
            session['tipo_user'] = tipo_user

            return redirect('/admin')
        elif tipo_user == 'ENC':
            #return redirect('/encargado')
            pass
        else:
            flash('Ocurrio un error inesperado al ingresar')
            return redirect(url_for('login.show_login'))
    else:
        flash('Nombre de usuario o contraseña incorrectos')
        return redirect(url_for('login.show_login'))


@login_bp.route('/cerrar-sesion')
def cerrar_session():
    session.pop('Nombre_Completo', None)
    session.pop('username', None) 
    session.pop('tipo_user', None)
    return redirect(url_for('login.show_login'))


# Ruta para los archivos del componente de Login
@login_bp.route('/login/static/<path:filename>')
def login_static(filename):
    return send_from_directory(login_bp.static_folder, filename)

app/templates/login/login.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('login.login_static', filename='login.css') }}"
    />
    <title>Login</title>
  </head>
  <body>
    <div class="login-container">
      <form id="login-form" action="{{ url_for('login.login') }}" method="POST">
        <h2>Iniciar Sesión</h2>
        <input
          type="text"
          name="username"
          placeholder="Nombre de usuario"
          required
        />
        <input
          type="password"
          name="password"
          placeholder="Contraseña"
          required
        />
        <button type="submit">Ingresar</button>
      </form>
      <div id="error-message">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                    <p>{{messages[-1]}}</p>
            {% endif %} 
        {% endwith %}
      </div>
    </div>

    

    <script src="{{ url_for('login.login_static', filename='login.js') }}"></script>
  </body>
</html>

app/templates/shared/registrar-nuevo-tramite/registrar-nuevo-tramite.html
<style>
    .bx {
        min-width: 600px;
        margin: 5px auto;
        padding: 20px;
        background-color: #FCFCFC;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .bx-form > h2 {
        font-weight: normal;
        padding: 5px;
        border-bottom: 2px solid #636a74;
        margin-bottom: 10px;
    }
    .bx-form {
        display: flex;
        flex-direction: column;
    }

    .bx-form label {
        margin-bottom: 15px;
    }

    .bx-form input[type="text"],
    .bx-form input[type="tel"],
    .bx-form input[type="datetime-local"],
    .bx-form select,
    .bx-form textarea {
        padding: 5px;
        font-size: 1rem;
        border: 1px solid #aaa;
        border-radius: 4px;
        transition: border-color 0.3s;
        background-color: #ffffff;
    }

    .bx-form input[type="text"]:focus,
    .bx-form input[type="tel"]:focus,
    .bx-form input[type="datetime-local"]:focus,
    .bx-form select:focus,
    .bx-form textarea:focus {
        border-color: #5e81ac;
        outline: none;
    }
    .bx-buscar-persona input[type="submit"],
    .bx-form input[type="submit"] {
        padding: 5px;
        font-size: 1rem;
        color: #ffffff;
        background-color: #5e81ac;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .bx-form input[type="submit"]:hover {
        background-color: #4c566a;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    table th, table td {
        padding: 10px;
        border: 1px solid #ccc;
        text-align: left;
    }

    table th {
        background-color: #e5e9f0;
    }

    #tramitadorSeleccionado,
    #propietarioSeleccionado {
        background-color: #f3f3f3;
    }

    #tableBusqueda button{
        margin: 2px;
        padding: 2px;
    }
    #tableBusqueda th:first-child{
        min-width: 210px;
        max-width: 300px;
    }
    #tableBusqueda th:nth-child(2){
        min-width: 150px;
    }
    .bx-buscar-persona{
        display: flex;
        gap: 10px;
    }
    .bx-buscar-persona input[type="search"]{ min-width: 300px; }

</style>

<div class="bx">
    <form class="bx-buscar-persona" onsubmit="return buscarTramitador(event)">
        <label for="carnet">
            <input type="search" name="SearchCarnet" id="SearchCarnet" placeholder="Buscar por CI" required>
        </label>
        <input type="submit" value="Buscar">
    </form>
    <div>
        <table id="tableBusqueda">
            <thead>
                <tr><th>Nombre completo</th><th>Carnet Identidad</th><th></th></tr>
            </thead>
            <tbody id="resBusqueda">
                <tr id="tr-1">
                    <td> </td>
                    <td> </td>
                    <td>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <form class="bx-form" onsubmit="return registrarTramite(event)">
        <h2>Datos del Trámite</h2>
        <table>
            <tr>
                <th>Tramitador</th><td id="tramitadorSeleccionado">-</td>
            </tr>
            <tr>
                <th>Propietario</th><td id="propietarioSeleccionado">-</td>
            </tr>
        </table>
        <label for="NroPatente">
            <input type="text" name="NroPatente" required placeholder="Numero de patente">
        </label>
        <label for="TipoTramite">
            <select name="TipoTramite" id="TipoTramite" required>
                <option value="" disabled selected>Seleccione un tipo de trámite</option>
                <option value="1">OpcionEjemplo1</option>
                <option value="2">OpcionEjemplo2</option>
            </select>
        </label>
        <label for="DescripcionDocumentosEntregados">
            <textarea name="DescripcionDocumentosEntregados" placeholder="Descripción de documentos entregados" required></textarea>
        </label>
        <label for="FechaEstimadaEntrega">
            <input type="date" name="FechaEstimadaEntrega" id="FechaEstimadaEntrega" required>
        </label>
        <input type="submit" value="Registrar Trámite">
    </form>
</div>

<script>
    let registro = {
        tramitador_id: null,
        propietario_id: null,
        tipo_tramite: null,
        descripcion_documentos_entregados: null,
        fecha_estimada_entrega: null,
        nro_patente: null
    };
    
    function buscarTramitador(event) {
        event.preventDefault();
        const carnet = document.getElementById('SearchCarnet').value;

        fetch(`/gestor_tramite/obtener_persona/${carnet}`)
            .then(response => response.json())
            .then(data => {
                if (typeof data.nombre === 'undefined') { alert("Persona no encontrada"); return; }
                document.getElementById("resBusqueda").innerHTML =/*html*/`
                <tr id="tr-1">
                    <td>${data.nombre} ${data.ap_paterno} ${data.ap_materno}</td>
                    <td>${data.ci}</td>
                    <td>
                        <button onclick="agregarTramitador('tr-1', '${data.id}')">Agregar como tramitador</button>
                        <button onclick="agregarPropietario('tr-1', '${data.id}')">Agregar como propietario</button>
                    </td>
                </tr>
                `;
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }


    function agregarTramitador(trId, id) {
        const trData = document.getElementById(trId);
        const tramitadorSeleccionado = document.getElementById('tramitadorSeleccionado');
        const nombre = trData.cells[0].innerText;
        const carnet = trData.cells[1].innerText;
        tramitadorSeleccionado.textContent = `${nombre}  | CI: ${carnet}`
        registro.tramitador_id = id;
    }

    function agregarPropietario(trId, id) {
        const trData = document.getElementById(trId);
        const propietarioSeleccionado = document.getElementById('propietarioSeleccionado');
        const nombre = trData.cells[0].innerText;
        const carnet = trData.cells[1].innerText;
        propietarioSeleccionado.textContent = `${nombre}  | CI: ${carnet}`
        registro.propietario_id = id;
    }

    function registrarTramite(event) {
        event.preventDefault();
        const tipoTramite = document.getElementById('TipoTramite').value;
        const descripcion = document.querySelector('textarea[name="DescripcionDocumentosEntregados"]').value;
        const fechaEntrega = document.querySelector('input[name="FechaEstimadaEntrega"]').value;
        const nroPatente = document.querySelector('input[name="NroPatente"]').value;
        registro.descripcion_documentos_entregados = descripcion;
        registro.fecha_estimada_entrega = fechaEntrega;
        registro.tipo_tramite = tipoTramite;
        registro.nro_patente = nroPatente;
        console.log(registro)
        for (let atr in registro) {
            if (registro[atr] == null) {
                alert(`Falta el valor de ${atr}`);
                return;
            }
        }
        fetch(`/gestor_tramite/registrar_tramite`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(registro)
            })
            .then(response => response.json())
            .then(data => {
                alert("Tramite registrado con éxito");
            })
            .catch(error => {
                console.error('Error:', error);
                alert("Ocurrio un error en servidor.");
            });
    }
</script>

app/templates/shared/registrar-tramitador/registrar-tramitador.html
<style>
    .bx {
        max-width: 600px;
        margin: 5px auto;
        padding: 20px;
        background-color: #FCFCFC;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .bx-form>h2{
        font-weight: normal;
        padding: 5px;
        border-bottom:2px solid #636a74;
        margin-bottom: 10px;
    }
    .bx-form {
        display: flex;
        flex-direction: column;
    }

    .bx-form label {
        margin-bottom: 15px;
    }

    .bx-form input[type="text"],
    .bx-form input[type="tel"] {
        padding: 5px;
        font-size: 1rem;
        border: 1px solid #aaa;
        border-radius: 4px;
        transition: border-color 0.3s;
        background-color: #ffffff;
    }

    .bx-form input[type="text"]:focus,
    .bx-form input[type="tel"]:focus {
        border-color: #5e81ac;
        outline: none;
    }

    .bx-form input[type="submit"] {
        padding: 5px;
        font-size: 1rem;
        color: #ffffff;
        background-color: #5e81ac;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .bx-form input[type="submit"]:hover {
        background-color: #4c566a;
    }
 
</style>

<div class="bx">
    <form class="bx-form" onsubmit="return registrarPersona(event)">
        <h2>Registrar Persona</h2>
        <label for="nombre">
            <input type="text" name="Nombre" id="nombre" placeholder="Nombre" required>
        </label>
        <label for="apellido-paterno">
            <input type="text" name="ApellidoPaterno" id="apellido-paterno" placeholder="Apellido Paterno" required>
        </label>
        <label for="apellido-materno">
            <input type="text" name="ApellidoMaterno" id="apellido-materno" placeholder="Apellido Materno" required>
        </label>
        <label for="carnet">
            <input type="text" name="Carnet" id="carnet" placeholder="Carnet de identidad" required>
        </label>
        <label for="telefono">
            <input type="tel" name="Tel" id="telefono" placeholder="Teléfono" required>
        </label>
        <label for="direccion">
            <input type="text" name="Direccion" id="direccion" placeholder="Dirección" required>
        </label>
        <input type="submit" value="Registrar">
    </form>
</div>

<script>
    function registrarPersona(event) {
        event.preventDefault();
        const rBody = {
            carnet: document.querySelector('input[name="Carnet"]').value,
            nombre: document.querySelector('input[name="Nombre"]').value,
            ap_paterno: document.querySelector('input[name="ApellidoPaterno"]').value,
            ap_materno: document.querySelector('input[name="ApellidoMaterno"]').value,
            tel: document.querySelector('input[name="Tel"]').value,
            direccion: document.querySelector('input[name="Direccion"]').value,
        };

        fetch(`/gestor_tramite/registrar_persona`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(rBody)
            })
            .then(response => response.json())
            .then(data => {
                alert("Persona registrada con éxito");
            })
            .catch(error => {
                console.error('Error:', error);
                alert("Ocurrio un error en servidor.");
            });
    }
</script>

app/templates/shared/side-bar/side-bar.html
<style>
  .sidebar {
      width: 250px;
      background-color: #3b3b3b;
      height: 100vh;
      padding: 20px;
      box-shadow: 2px 0 5px rgba(0, 0, 0, 0.2);
  }

  .sidebar h1 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #eceff4;
  }

  .sidebar ul {
      list-style: none;
      padding: 0;
  }

  .sidebar ul li {
      margin: 15px 0;
  }

  .sidebar ul li a,
  .sidebar a {
      text-decoration: none;
      color: #d8dee9;
      padding: 10px;
      display: block;
      border-radius: 4px;
      transition: background 0.3s, color 0.3s;
  }

  .sidebar ul li a:hover,
  .sidebar a:hover {
      background-color: #4c566a;
      color: #ffffff; 
  }

  .last-item {
      margin-top: auto;
      font-weight: bold;
  }

  .content {
      margin-left: 260px;
      padding: 20px;
      width: calc(100% - 260px);
      transition: margin-left 0.3s;
  }

  @media (max-width: 768px) {
      .sidebar {
          width: 200px;
      }

      .content {
          margin-left: 220px;
          width: calc(100% - 220px);
      }
  }

  @media (max-width: 480px) {
      .sidebar {
          width: 100%;
          height: auto;
          position: relative;
      }

      .content {
          margin-left: 0;
          width: 100%;
      }
  }
</style>

<div class="sidebar">
  <h1>Trámites</h1>
  <ul>
      {% for item in sidebar_items %}
          <li><a href="{{ item.path }}">{{ item.item_name }}</a></li>
      {% endfor %}
  </ul>
  <a href="/cerrar-sesion" class="last-item">Cerrar sesión</a>
</div>
<script type="module">
  // Tu script aquí
</script>

app/templates/tramite/tramite.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ver tramite</title>
    <link
        rel="stylesheet"
        href="{{ url_for('static', filename='styles.css') }}"
    />
    <style>
        body{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background:
      radial-gradient(35.36% 35.36% at 100% 25%,#0000 66%,#308440 68% 70%,#0000 72%) 100px 100px/calc(2*100px) calc(2*100px),
      radial-gradient(35.36% 35.36% at 0    75%,#0000 66%,#308440 68% 70%,#0000 72%) 100px 100px/calc(2*100px) calc(2*100px),
      radial-gradient(35.36% 35.36% at 100% 25%,#0000 66%,#308440 68% 70%,#0000 72%) 0 0/calc(2*100px) calc(2*100px),
      radial-gradient(35.36% 35.36% at 0    75%,#0000 66%,#308440 68% 70%,#0000 72%) 0 0/calc(2*100px) calc(2*100px),
      repeating-conic-gradient(#cdd4cf 0 25%,#0000 0 50%) 0 0/calc(2*100px) calc(2*100px),
      radial-gradient(#0000 66%,#308440 68% 70%,#0000 72%) 0 calc(100px/2)/100px 100px
      #cdd4cf;

        }
        .flex{
            display: flex;
        }
        .box-buscador, .card-resultado{
            width: 600px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 20px;
            background: rgba(255,255,255,0.55);
            -webkit-backdrop-filter: blur(25px);
            backdrop-filter: blur(25px);
            border: 1px solid rgba(255,255,255,0.275);
        }
        .box-buscador input[type="submit"]{
            width: 100px;
        }
        
    </style>
</head>
<body>

    <div class="box-buscador">
        <h1>Tramites Cotoca</h1>
        <form action="/ver_tramite" method="POST" class="flex">
            <input type="text" name="codigo" placeholder="Codigo de Tramite">
            <input type="submit" value="Buscar">
        </form>
    </div>

    <div class="box-resultado">
        {% if tramite %}
        <div class="card-resultado">
            <p>Codigo de tramite: {{ tramite.id }}</p>
            <p>Fecha de Fin Probable: {{ tramite.fecha_fin_probable }}</p>
            <p>Estado: {{ tramite.nombre_estado }}</p>
        </div>
        {% else %}
        <div class="card-resultado">
            <p>Trámite no disponible</p>
        </div>
        {% endif %}
    </div>

    <script>

    </script>
</body>
</html>